### ISSUE TITLE
QA - SPARK CONNECTOR - seems to be quite slower than vwload -c with multiple files

### ISSUE THREAD

**Issue by vishalpsheth** [ActianCorp/spark-vector#11]
# # **Description**

Hi,
some observations on our QA clusters. Maybe you can try locally and see if it looks the same. 
Andrei said it should be close to vwload -c even with YARN overhead.

Machine Info: (all 4 node clusters)

Cloudera: CDH 5.5.1 , Spark 1.5.0
uksl-kelch01-cent6-clu1
32GB ram, 4 cores

Hortonworks: HDP 2.3.4 , Spark 1.5.2
uksl-vortexqa-hdp22-clu1.actian.com
16GB ram, 2 cores

MapR: 5.0 , Spark 1.5.2
uksl-indecomm-mapR-clu1 
16Gb ram, 2 cores

table to be loaded lineitem 7 GB file.

scenario 1: vwload and local table
###### 

vwload -t lineitem sample /mnt/stressdb/lineitem.tbl

CDH: 3 min
HDP: 3,5 min 
MapR: 2,x mins 

scenario 2: vwload -c and single hdfs file
###### 

vwload -c -t lineitem sample /mapr/my.cluster.com/Actian/tmp/parts/lineitem.tbl
CDH: 3 min
HDP: 6 min
MapR: 4 min 

scenario 3: vwload -c and multiple hdfs files
###### 

vwload -c -t lineitem sample $(hadoop fs -ls /mapr/my.cluster.com/Actian/tmp/parts/x\* | grep -o "/mapr.*$")

CDH: 1 min
HDP: 2 min
MapR: 1 min 

scenario 4: Spark job YARN
###### 

$ spark-submit....

CDH: 3 min
HDP: 14 min
MapR: 13 min

**Comment by and-costea** [comment]
After investigation, most of the time spent during execution is in the parsing library (spark-csv). There is little time spent in serialization of data values (there are however some performance issues regarding decimals that we plan to address), but in all there is little time spent in the connector code itself.

Closing for now.
