### ISSUE TITLE
0008199: QA - SPARK CONNECTOR - unload of character data some inconsistencies

### ISSUE THREAD

**Issue by Pyrobal** [ActianCorp/spark-vector#18]
Hi,
unloaded a character table and got some different results.
Not sure if the NULL representation is correct as a space. Also \ gets converted into \ and two special characters have double brakets around them whil other do not.

loaded charatcer file was: /home/actian/kelch01/svn_main_checkout/vectorwise/fastload/data/character.txt

CREATE TABLE tab_CHAR1 (col1 int, col2 CHAR(1));\g

+-------------+------+
|col1         |col2  |
+-------------+------+
|            1|N     |
|            2|a     |
|            3|z     |
|            4|A     |
|            5|Z     |
|            6|0     |
|            7|1     |
|            8|9     |
|            9|~     |
|           10|!     | --> 10,"!"  (not sure why it got "" around it while all 
others except Null do not have them)
|           11|@     |
|           12|#     | --> 12,"#"  (not sure why it got "" around it while all 
others except Null do not have them)
|           13|$     |
|           14|%     |
|           15|^     |
|           16|&     |
|           17|\*     |
|           18|(     |
|           19|)     |
|           20|+     |
|           21|_     |
|           22|=     |
|           23|[     |
|           24|]     |
|           25|{     |
|           26|}     |
|           27|\    |  -->  27,\
|           28||     |
|           29|;     |
|           30|:     |
|           32|.     |
|           33|<     |
|           34|>     |
|           35|/     |
|           36|?     |
|           37|'     |
|           38|+     |
|           39|.     |
|           40|      |  -->  40," "
|           41|N     |
|           42|T     |
|           43|T     |
|           44|      |  -->  44," "
|           45|-     |
|           46|-     |
|           47|0     |
|           48|5     |
|           49|2     |
|           50|      |  -->  50," "
|           51|T     |
+-------------

**Comment by Pyrobal** [comment]
unlaoding 20 characters column NULL values are created

5,"Z                   "
6,"0                   "
17,"\*                   "
18,"(                   "
19,")                   "
30,":                   "
32,".                   "
43,"TEST                "
44,"  TEST              "
45,"-3                  "
4,"A                   "
5,"Z                   "
6,"0                   "
17,"\*                   "
18,"(                   "
19,")                   "
30,":                   "
32,".                   "
43,"TEST                "
44,"  TEST              "
45,"-3                  "
4,"A                   "
33,"<                   "
35,"/                   "
40,"                    "
42,"TEST                "
47,"0                   "
2,"a                   "
7,"1                   "
9,"~                   "
14,"%                   "
16,"&                   "
21,"_                   "
26,"}                   "
28,"|                   "
2,"a                   "
7,"1                   "
9,"~                   "
14,"%                   "
16,"&                   "
21,"_                   "
26,"}                   "
28,"|                   "
33,"<                   "
35,"/                   "
40,"                    "
42,"TEST                "
47,"0                   "
12,"#                   "
23,"[                   "
24,"]                   "
25,"{                   "
36,"?                   "
37,"'                   "
38,"+                   "
49,"2007-11-18          "
36,"?                   "
37,"'                   "
38,"+                   "
49,"2007-11-18          "
50,"                    "
51,"TESTTESTTEST        "
10,"!                   "
11,"@                   "
50,"                    "
51,"TESTTESTTEST        "
10,"!                   "
11,"@                   "
12,"#                   "
23,"[                   "
24,"]                   "
25,"{                   "
1,"NULL                "
3,"z                   "
8,"9                   "
13,"$                   "
15,"^                   "
20,"+                   "
22,"=                   "
27,"\                   "
29,";                   "
20,"+                   "
22,"=                   "
27,"\                   "
29,";                   "
34,">                   "
39,".<>/?'+             "
41,"NULL                "
46,"-0                  "
48,"5                   "
34,">                   "
39,".<>/?'+             "
41,"NULL                "
46,"-0                  "
48,"5                   "
1,"NULL                "
3,"z                   "
8,"9                   "
13,"$                   "
15,"^                   "

**Comment by and-costea** [comment]
`spark-shell --master yarn --jars /home/actian/kelch01/Spark/spark-loader/spark-vector/target/spark_vector-assembly-0.1.jar --packages com.databricks:spark-csv_2.10:1.4.0`

and then:
`sqlContext.sql("""CREATE TEMPORARY TABLE tab_char1
USING com.actian.spark_vector.sql.DefaultSource
OPTIONS (
host "uksl-kelch01-cent6-clu1",
instance "K1",
database "testdb",
table "tab_char1",
user "actian",
password "actian")""")`

`val tab = "\t"`
`sqlContext.sql("select * from tab_char1 order by col1").write.format("com.databricks.spark.csv").options(Map("quoteMode" -> "NONE", "escape" -> "\\", "delimiter" -> s"$tab")).save("/Actian/tmp/something4")`

returns the expected results (-1 row 31 since it interprets the single \ character as an escape character).

Also, I don't think there are any null values in this test, e.g. rows 44 and 50 contain spaces.

"quoteMode" is a feature introduced in Feb 2016 by spark-csv (let's you specify how much quoting you want. Before, it would always do as they saw fit.)

**Comment by and-costea** [comment]
Also, maybe a good way of seeing how spark-csv parses stuff:

`val tab = "\t"`
`sqlContext.sql(s"""CREATE TEMPORARY TABLE csv_tab_char1
USING com.databricks.spark.csv
OPTIONS (
escape "\\",
path "/Actian/tmp/character.txt",
delimiter "$tab"
)""")`

`sqlContext.sql("select * from csv_tab_char1").write.format("com.databricks.spark.csv").options(Map("quoteMode" -> "NONE", "escape" -> "\\", "delimiter" -> s"$tab")).save("/Actian/tmp/something3")`

**Comment by Pyrobal** [comment]
not an issue anymore. 
closing
