### ISSUE TITLE
QA - SPARK CONNECTOR - parallel unload: wrong values unloaded for character datatype

### ISSUE THREAD

**Issue by Pyrobal** [ActianCorp/spark-vector#26]
Biggest issue is complete wrong value for the first rows which seems to get converted to nulls.

This is 4.2.3 with path and manually provided jar from Cristi. 

$ hadoop fs -cat /Actian/VectorK2/tab_CHAR1.csv/part*
1,null
2,null
3,null
4,null
5,Z
6,0
7,1
8,9
9,~
10,"!"
11,@
12,"#"
..
- select \* from tab_char1\g
  Executing . . .
  +-------------+------+
  |col1         |col2  |
  +-------------+------+
  |            1|      |
  |            2|a     |
  |            3|z     |
  |            4|A     |
  |            5|Z     |
  |            6|0     |
  |            7|1     |
  |            8|9     |
  |            9|~     |
  |           10|!     |

TESTCASE:
###### 

take character.txt attached to the issue:

CREATE TABLE tab_CHAR1 (col1 int, col2 CHAR(1));\g
COPY TABLE tab_CHAR1 (col1 = c0tab, col2  = c0nl WITH NULL('NULL')) FROM 'character.txt'\g

export SEPPARAMDB=testdb
export SPARK_MASTER=${SPARK_MASTER:-yarn}
export TMP_II_INSTALLATION=${TMP_II_INSTALLATION:-$(iigetenv II_INSTALLATION)}
export TMP_HOSTNAME=${TMP_HOSTNAME:-$HOSTNAME}
export HDFS_TMP=${HDFS_TMP:-$(iigetenv II_HDFSDATA)}
export SPARK_LOADER_JAR=/home/actian/kelch01/Spark/unloader/spark_vector_loader-assembly-0.1.jar

val savepath =sys.env("HDFS_TMP")
val installation_ID= sys.env("TMP_II_INSTALLATION")
val hostname= sys.env("TMP_HOSTNAME")
val databasename= sys.env("SEPPARAMDB")

sqlContext.sql(s"""CREATE TEMPORARY TABLE tab_CHAR1
USING  com.actian.spark_vector.sql.DefaultSource
OPTIONS (
    host "$hostname",
    instance "$installation_ID",
    database "$databasename",
    table "tab_CHAR1",
    user "actian",
    password "actian")""")

sqlContext.sql("select \* from tab_CHAR1").write.format("com.databricks.spark.csv").save(s"$savepath/tab_CHAR1.csv")

**Comment by cbarca** [comment]
create table tab_chartest2(col1 int, col2 char(1));\g
Executing . . .

continue

copy table tab_chartest2(col1=c0tab,col2=c0nl with NULL('NULL')) from '/home/users/cristi/character.txt';\g
Executing . . .

(10 rows)
continue
select \* from tab_chartest2;\g
Executing . . .

┌─────────────┬──────┐
│col1         │col2  │
├─────────────┼──────┤
│            1│      │
│            2│a     │
│            3│b     │
│            4│c     │
│            5│d     │
│            6│e     │
│            7│"     │
│            8│?     │
│            9│#     │
│           10│!     │
└─────────────┴──────┘
(10 rows)
continue

From Spark unload:
res1: Array[org.apache.spark.sql.Row] = Array([3,b], [7,"], [4,c], [5,d], [10,!], [1,null], [6,e], [8,?], [2,a], [9,#])

should be fixed now, waiting for feedback

**Comment by cbarca** [comment]
fixed in external-insert branch

**Comment by cbarca** [comment]
fixed in master too, closing
