### ISSUE TITLE
QA - SPARK Parallel unloader - no data exported for particular query

### ISSUE THREAD

**Issue by Pyrobal** [ActianCorp/spark-vector#44]
Hi,
this query should export 14 rows but it does not export anything.

5.0H latest daily and latest spark 1.0 jar. 

scala> sqlContext.sql("select col_float4,col_int,col_nvarchar, col_timestamp,col_ansidate from vwload_reg02_unload_tbl where col_timestamp IN ('2007-11-18 00:00:00.000000001') and col_nvarchar IN ('abcdefghijklmnopqrst','K','D','TEST TEST','J','E')").write.format("com.databricks.spark.csv").save(s"$savepath/vwload_reg02_unload_tbl_07.csv")

$ hadoop fs -cat /Actian/VectorK2/vwload_reg02_unload_tbl_07.csv/part*
actian@uksl-kelch01-cent6-clu1  K2  09:27:37  ~

select col_float4,col_int,col_nvarchar, col_timestamp,col_ansidate from vwload_reg02_unload_tbl where col_timestamp IN ('2007-11-18 00:00:00.000000001') and col_nvarchar IN ('abcdefghijklmnopqrst','K','D','TEST TEST','J','E')\g
Executing . . .

+-----------+-------------+----------------------------------------+---------------------------------------+----------+
|col_float4 |col_int      |col_nvarchar                            |col_timestamp                          |col_ansida|
+-----------+-------------+----------------------------------------+---------------------------------------+----------+
|-1.701e+038|      -123456|TEST TEST                               |2007-11-18 00:00:00.000000             |2012-01-01|
|           |             |abcdefghijklmnopqrst                    |2007-11-18 00:00:00.000000             |2012-12-31|
| 1.701e+038|            0|abcdefghijklmnopqrst                    |2007-11-18 00:00:00.000000             |2012-12-31|
| 1.701e+038|            0|abcdefghijklmnopqrst                    |2007-11-18 00:00:00.000000             |2012-12-31|
|-1.701e+038|             |TEST TEST                               |2007-11-18 00:00:00.000000             |2012-01-01|
|-1.701e+038|      -123456|TEST TEST                               |2007-11-18 00:00:00.000000             |2012-01-01|
| 1.701e+038|            0|abcdefghijklmnopqrst                    |2007-11-18 00:00:00.000000             |2012-12-31|
| 1.701e+038|            0|abcdefghijklmnopqrst                    |2007-11-18 00:00:00.000000             |          |
|     29.000|           29|D                                       |2007-11-18 00:00:00.000000             |2012-02-10|
|-1.701e+038|      -123456|TEST TEST                               |2007-11-18 00:00:00.000000             |2012-01-01|
| 1.701e+038|            0|abcdefghijklmnopqrst                    |2007-11-18 00:00:00.000000             |2012-12-31|
|     30.000|           30|E                                       |2007-11-18 00:00:00.000000             |2012-03-01|
|     35.000|           35|J                                       |2007-11-18 00:00:00.000000             |2012-03-06|
|     36.000|           36|K                                       |2007-11-18 00:00:00.000000             |2012-03-07|
+-----------+-------------+----------------------------------------+---------------------------------------+----------+
(14 rows)

TESTCASE:

use attached data file

create table vwload_reg02_unload_tbl (col_int int, col_float4 float4, col_money money,col_decimal382 decimal(38,2),col_decimal102 decimal(10,2), col_char20 char(20), col_varchar20 varchar(20), col_nchar20 nchar(20),col_nvarchar nvarchar(20), col_ansidate ansidate, col_timestamp timestamp);\g

vwload --nullvalue NULL --fdelim "\t" --table vwload_reg02_unload_tbl SEPPARAMDB vwload_reg02_data.txt

create table vwload_reg02_unload_tbl2 as select \* from vwload_reg02_unload_tbl\g

val savepath =sys.env("HDFS_TMP")
val installation_ID= sys.env("TMP_II_INSTALLATION")
val hostname= sys.env("TMP_HOSTNAME")
val databasename= sys.env("SEPPARAMDB")
val user = sys.env.get("II_USER")
val password = sys.env.get("II_PASSWORD")

val usernameAndPasswordStatement = (user, password) match {
case (Some(u), Some(p)) => s""", user "$u", password "$p""""
case _ => ""
}

sqlContext.sql(s"""CREATE TEMPORARY TABLE vwload_reg02_unload_tbl
USING  com.actian.spark_vector.sql.DefaultSource
OPTIONS (
    host "$hostname",
    instance "$installation_ID",
    database "$databasename",
    table "vwload_reg02_unload_tbl"
    $usernameAndPasswordStatement)""")

sqlContext.sql(s"""CREATE TEMPORARY TABLE vwload_reg02_unload_tbl2
USING  com.actian.spark_vector.sql.DefaultSource
OPTIONS (
    host "$hostname",
    instance "$installation_ID",
    database "$databasename",
    table "vwload_reg02_unload_tbl2"
    $usernameAndPasswordStatement)""")

sqlContext.sql("select col_float4,col_int,col_nvarchar, col_timestamp,col_ansidate from vwload_reg02_unload_tbl where col_timestamp IN ('2007-11-18 00:00:00.000000001') and col_nvarchar IN ('abcdefghijklmnopqrst','K','D','TEST TEST','J','E')").write.format("com.databricks.spark.csv").save(s"$savepath/vwload_reg02_unload_tbl_07.csv")

**Comment by cbarca** [comment]
wrong precision used for selecting timestamp IN
