### ISSUE TITLE
 QA - SPARK Parallel unloader - hangs on join query

### ISSUE THREAD

**Issue by Pyrobal** [ActianCorp/spark-vector#47]
use testcase from https://mantis-vw.actian.com/view.php?id=8413 [^] BUT also do the following: "delete from vwload_reg02_unload_tbl2 where mod(col_int,2)= 0\g"

now run:

scala> sqlContext.sql("select vwload_reg02_unload_tbl.col_int, vwload_reg02_unload_tbl.col_char20 from vwload_reg02_unload_tbl2 right join vwload_reg02_unload_tbl on vwload_reg02_unload_tbl.col_int=vwload_reg02_unload_tbl2.col_int where vwload_reg02_unload_tbl.col_int <= 140 and vwload_reg02_unload_tbl.col_int > 70").write.format("com.databricks.spark.csv").save(s"$savepath/vwload_reg02_unload_tbl_17.csv")

hangs

**Comment by cbarca** [comment]
Cannot repro this one :(  
It doesn't hang for me...

16/06/02 12:31:37 INFO DAGScheduler: Job 1 finished: collect at <console>:22, took 1.962304 s
16/06/02 12:31:37 DEBUG DataStreamClient: Rollback current transaction and close DataStreamClient
res5: Array[org.apache.spark.sql.Row] = Array([71,small], [72,big], [73,lazy], [74,Germany], [75,England], [76,USA], [77,yellow], [78,abcdefghijklmnopqrst], [79,1234567890], [80,9999999999], [81,paper], [82,ß], [83,Ö], [84,Ü], [85,Ä], [86,!!!!!!!!!!!!!!], [87,fdjg], [88,hrt], [89,s5srtbgfnw5SDF], [90,sdfgsdg], [91,  m  m  m  m], [92,<<<<<<<<], [93,>>>>>>>>], [94,left], [95,right], [96,middle], [97,fish], [98,sea], [99,trawler], [100,onehundred])

**Comment by Pyrobal** [comment]
sorry I closed the mantis issue already, forgot this one. Does not hang for me either anymore.
